name: 1 - Hello World GitHub Actions

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello there
        run: echo 'hello'
