name: 1 - Hello World GitHub Actions

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 15 * * *'
  # push:
  #   branches:
  #     - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello there
        run: echo 'hello'
